-- Help for DPS commands
cecho("<cyan>DPS Help\n")
cecho("<white>Usage:\n")
cecho("<white>  dps [help]                 Show this help\n")
cecho("<white>  dps start <name>          Start a new session under <name>\n")
cecho("<white>  dps stop                   Stop the current session\n")
cecho("<white>  dps report [name]         Show totals for <name> or all (via compare)\n")
cecho("<white>  dps compare                Compare all strategies (sorted by raw DPS)\n")
cecho("<white>  dps setname <name>        Set auto session label used by auto-start\n")
cecho("<white>  dps rename <old> <new>    Rename strategy <old> to <new>\n")
cecho("<white>  dps delete <name>         Delete strategy <name> (all sessions)\\n")
cecho("<white>Notes:\n")
cecho("<white>  - Tracks crits and computes raw DPS (crit multipliers removed).\n")
cecho("<white>  - Tallies damage by type when seen (e.g., psychic, fire).\n")
cecho("<white>  - Auto-starts on first damage, pauses on regain if not attacking.\n")
cecho("<white>  - Persists sessions to @PKGNAME@/dps_data.json.\n")
