-- Help for DPS commands
cecho("<cyan>DPS Help\n")
cecho("<white>Usage:\n")
cecho("<white>  dps [help]                 Show this help\n")
cecho("<white>  dps start <name>          Start a new session under <name>\n")
cecho("<white>  dps stop                   Stop the current session\n")
cecho("<white>  dps status                 Show current session DPS without stopping\n")
cecho("<white>  dps setname <name>        Set auto session label used by auto-start\n")
cecho("<white>  dps local [enemy]         Local leaderboard for current/specified enemy name\n")
cecho("<white>  dps enemy <enemy>         Local leaderboard for the given enemy name\n")
cecho("<white>  dps enemies               List enemies with recorded local data\n")
cecho("<white>  dps overview [strat]      Compare enemies by DPS for strategy [strat]\n")
cecho("<white>  dps reset <enemy> [:: <strat>] Reset local data (enemy or enemy+strategy)\n")
cecho("<white>  dps setlastn <N>          Set recent sessions buffer size (default 10)\n")
cecho("<white>  dps rename <from> -> <to> Rename enemy; merges if <to> exists\n")
cecho("<white>  dps merge <from> -> <to>  Merge <from> into existing <to>\n")
cecho("<white>Notes:\n")
cecho("<white>  - Tracks crits and computes raw DPS (crit multipliers removed).\n")
cecho("<white>  - Tallies damage by type when seen (e.g., psychic, fire).\n")
cecho("<white>  - Attributes encounters per enemy name using GMCP target + room items.\n")
cecho("<white>  - Keeps totals plus last-N recent sessions for local comparisons.\n")
cecho("<white>  - Auto-starts on first damage, pauses on regain if not attacking.\n")
cecho("<white>  - Persists sessions to @PKGNAME@/dps_data.json.\n")
